### ISSUE TITLE
Shadow below addressbar is too thick

### ISSUE THREAD

**Issue by PalmerAL** [liri-project/liri-browser#75]
The shadow distracts from the webpage a lot, and isn't material-like either - compare the shadow to http://www.google.com/design/spec/material-design/introduction.html#introduction-principles.

Might be a qml-material issue.

**Comment by tim-sueberkrueb** [comment]
@PalmerAL 
https://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-elevation-android-
App bar: 4dp elevation?

**Comment by pierremtb** [comment]
@PalmerAL Regarding Material specs, we're good. However, I agree with @PalmerAL, this shadow should be smaller.

**Comment by tim-sueberkrueb** [comment]
@pierremtb @PalmerAL I'm personally happy with the shadow. This is actually funny because in the past it was thinner and someone complained it was not thick enough. What elevation would you suggest?

**Comment by pierremtb** [comment]
Well there is no shadow anymore (I don't know why). I close this for now

**Comment by tim-sueberkrueb** [comment]
I believe you disabled the shadow because it looks odd in combination with the CSD. Please keep things like this open if there is no solution otherwise we'd forget them.

**Comment by pierremtb** [comment]
@tim-sueberkrueb Yeah you're right (for both). By the way I think that it looks better without any toolbar shadow, because when color option is enabled, there is very nice continuity (I don't know if it's the right word sorry) between the website header and the toolbar. Just my opinion, I think an option would be great (maybe a slider, from 0dp to 4dp). I will look into it (especially with CSD).

I was talking of something like that : 
![capture du 2015-10-06 17 58 47](https://cloud.githubusercontent.com/assets/10795683/10314296/5eb8f618-6c54-11e5-8698-0fa43b69215b.png)

**Comment by tim-sueberkrueb** [comment]
@pierremtb yeah, an option would be the best thing.

**Comment by VirusKA** [comment]
yeah i agree. options are the best.

**Comment by VirusKA** [comment]
any update on this. i'm feeling leave it the way it is now.

**Comment by tim-sueberkrueb** [comment]
Currently there is no shadow at all, but I personally think there should be one do make the difference between page and toolbar clearer.

**Comment by VirusKA** [comment]
yeah a little shadow will be nice

**Comment by VirusKA** [comment]
soo...

**Comment by VirusKA** [comment]
i like it the way it is

**Comment by pierremtb** [comment]
I've been playing around with this shadow. Here are some screenshots with different metrics on the same website : the new MD version of G+

- no shadow 
![capture d ecran de 2015-12-30 14-38-26](https://cloud.githubusercontent.com/assets/10795683/12052630/417119a0-af11-11e5-971d-98279221ba7d.png)

- 1dp
![capture d ecran de 2015-12-30 16-16-40](https://cloud.githubusercontent.com/assets/10795683/12052648/6f029754-af11-11e5-8cb1-8d3a56cb4fc0.png)

- 2dp
![capture d ecran de 2015-12-30 16-17-29](https://cloud.githubusercontent.com/assets/10795683/12052653/77fa121a-af11-11e5-875e-661f42fd9484.png)

IMO, this toolbar shadow is a bit "too much" on a MD website, that uses a MD toolbar too.
Another thing : there is no way to use the ink animation with a elevated toolbar, because it needs to be transparent to let the ink go under, which isn't possible with a shadow (because shadows in Qt are rectangles that go under the targeted component). Maybe we could make it optional : either you choose an elevated toolbar without the ink animation, or you choose a flat toolbar, with the ink animation.

**Comment by VirusKA** [comment]
Yeah I agree, the shadow will be too busy on a MD website.

**Comment by pierremtb** [comment]
Well, let's follow our guidelines : when we don't know, we add an option :) 
![capture d ecran de 2015-12-30 18-12-33](https://cloud.githubusercontent.com/assets/10795683/12054169/0dd2f23e-af21-11e5-8c2f-05e01b1feb1d.png)
